/*******************************************************************************
 Copyright (c) 2013-2014 Koninklijke Philips N.V.
 All Rights Reserved.
 ********************************************************************************/

#import "PHHeartbeatBridgeResourceType.h"
#import "PHBridgeResourcesCache.h"
#import "PHBridgeResourcesReader.h"
#import "PHBridgeSearching.h"
#import "PHBridgeSendAPI.h"
#import "PHBridgeConfiguration.h"
#import "PHError.h"
#import "PHParseError.h"
#import "PHGroup.h"
#import "PHLight.h"
#import "PHLightState.h"
#import "PHSchedule.h"
#import "PHScene.h"
#import "PHRule.h"
#import "PHRuleAction.h"
#import "PHSimpleRuleAction.h"
#import "PHRuleCondition.h"
#import "PHSimpleRuleCondition.h"
#import "PHSoftwareUpdateStatus.h"
#import "PHNotificationManager.h"
#import "PHHueSDK.h"
#import "PHBridgeResource.h"
#import "PHUtilities.h"
#import "PHDateTimePattern.h"
#import "PHRequest.h"
#import "PHPortalState.h"
#import "PHSoftwareUpdateStatusDeviceTypes.h"
#import "PHWhiteListEntry.h"

// Sensors
#import "PHSensor.h"
#import "PHSensorState.h"
#import "PHSensorConfig.h"
#import "PHGenericFlagSensor.h"
#import "PHGenericFlagSensorState.h"
#import "PHGenericFlagSensorConfig.h"
#import "PHGenericStatusSensor.h"
#import "PHGenericStatusSensorState.h"
#import "PHGenericStatusSensorConfig.h"
#import "PHSwitch.h"
#import "PHSwitchState.h"
#import "PHSwitchConfig.h"
#import "PHSwitchDeviceInfo.h"
#import "PHSwitchButtonInfo.h"
#import "PHSwitchButtonActionPair.h"
#import "PHOpenCloseSensor.h"
#import "PHOpenCloseSensorState.h"
#import "PHOpenCloseSensorConfig.h"
#import "PHPresenceSensor.h"
#import "PHPresenceSensorState.h"
#import "PHPresenceSensorConfig.h"
#import "PHGeofenceSensor.h"
#import "PHGeofenceSensorState.h"
#import "PHGeofenceSensorConfig.h"
#import "PHTemperatureSensor.h"
#import "PHTemperatureSensorState.h"
#import "PHTemperatureSensorConfig.h"
#import "PHHumiditySensor.h"
#import "PHHumiditySensorState.h"
#import "PHHumiditySensorConfig.h"
#import "PHDaylightSensor.h"
#import "PHDaylightSensorState.h"
#import "PHDaylightSensorConfig.h"